// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQCRdQRyc96c5h247VcusLY6Qvzj0KonQ',
    appId: '1:983611359117:web:a514a456df1790fe0507c4',
    messagingSenderId: '983611359117',
    projectId: 'blackcoffer-9ff19',
    authDomain: 'blackcoffer-9ff19.firebaseapp.com',
    storageBucket: 'blackcoffer-9ff19.appspot.com',
    measurementId: 'G-GW7M7EHLHX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE2kVNVT4_8YXcSQb9Q4HauTvKDfM7uS4',
    appId: '1:983611359117:android:1deb000cf79ed1770507c4',
    messagingSenderId: '983611359117',
    projectId: 'blackcoffer-9ff19',
    storageBucket: 'blackcoffer-9ff19.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsCSAG_zgIISqoeozeUDC_GtF4IYZ3f9w',
    appId: '1:983611359117:ios:7401e3dbd26ccc850507c4',
    messagingSenderId: '983611359117',
    projectId: 'blackcoffer-9ff19',
    storageBucket: 'blackcoffer-9ff19.appspot.com',
    iosBundleId: 'com.example.blackcoffer',
  );
}
